# Generated by Django 3.2.8 on 2021-11-01 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='')),
                ('Description', models.TextField()),
                ('Create_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Comment', models.TextField()),
                ('Create_by', models.CharField(max_length=100)),
                ('Create_at', models.DateField()),
                ('Post_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.post')),
            ],
        ),
    ]
