# Generated by Django 3.2.8 on 2021-11-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211106_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Post_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.post'),
        ),
    ]
