# Generated by Django 3.2.8 on 2021-11-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_comment_commenter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Create_by',
            field=models.CharField(max_length=512),
        ),
    ]
