# Generated by Django 3.2.8 on 2021-11-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_post_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Create_by',
            field=models.CharField(default='MBAdmin', max_length=512),
        ),
    ]
