# Generated by Django 3.2.8 on 2021-11-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_comment_commenter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Commenter_Name',
        ),
    ]
