# Generated by Django 3.2.8 on 2021-11-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_post_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Title',
            field=models.CharField(default='No Caption', max_length=512),
        ),
    ]
